"""
Nightreign Spells & Incantations - datamine-verified
Source: MagicTableParam + AtkParam_Pc for damage types

damage: Primary damage element (Physical/Magic/Fire/Lightning/Holy/Buff)
pools: which pool tables the spell appears in
starting_armament: True if rollable as a relic passive
"""

SORCERIES = {
    "Adula's Moonblade": {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Ambush Shard': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Ancient Death Rancor': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Briars of Punishment': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': True},
    'Briars of Sin': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Cannon of Haima': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Carian Greatsword': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': True},
    'Carian Phalanx': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Carian Piercer': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Carian Retaliation': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Carian Retaliation (Level 3)': {'damage': 'Buff/Utility', 'in_generic_pool': False, 'starting_armament': False},
    'Carian Retaliation (Level 4)': {'damage': 'Buff/Utility', 'in_generic_pool': False, 'starting_armament': False},
    'Carian Slicer': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Collapsing Stars': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Comet': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Comet Azur': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Crystal Barrage': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Crystal Burst': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Crystal Release': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Crystal Torrent': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Eternal Darkness': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Explosive Ghostflame': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Founding Rain of Stars': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Freezing Mist': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Frozen Armament': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Gavel of Haima': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    "Gelmir's Fury": {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Glintblade Phalanx': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Glintstone Arc': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Glintstone Cometshard': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Glintstone Icecrag': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Glintstone Pebble': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Glintstone Stars': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Gravity Well': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Great Glintstone Shard': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Great Oracular Bubble': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Greatblade Phalanx': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    "Loretta's Greatbow": {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    "Loretta's Mastery": {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Magic Downpour': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Magic Glintblade': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': True},
    'Magma Shot': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': True},
    'Meteorite': {'damage': 'Physical, Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Meteorite of Astel': {'damage': 'Physical, Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Night Comet': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    "Night Maiden's Mist": {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Night Shard': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': True},
    'Oracle Bubbles': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Rancorcall': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    "Ranni's Dark Moon": {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    "Rennala's Full Moon": {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Rock Blaster': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Rock Sling': {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': False},
    'Roiling Magma': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    "Rykard's Rancor": {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    "Scholar's Armament": {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Scholar's Shield": {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Shard Spiral': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Shatter Earth': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Shattering Crystal': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Star Shower': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Stars of Ruin': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Swift Glintstone Shard': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
    'Terra Magica': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Thops's Barrier": {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Tibia's Summons": {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Zamor Ice Storm': {'damage': 'Magic', 'in_generic_pool': True, 'starting_armament': False},
}

INCANTATIONS = {
    "Agheel's Flame": {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    "Ancient Dragons' Lightning Spear": {'damage': 'Lightning', 'in_generic_pool': False, 'starting_armament': False},
    "Ancient Dragons' Lightning Strike": {'damage': 'Lightning', 'in_generic_pool': False, 'starting_armament': False},
    'Aspects of the Crucible: Breath': {'damage': 'Fire', 'in_generic_pool': True, 'starting_armament': False},
    'Aspects of the Crucible: Horns': {'damage': 'Physical', 'in_generic_pool': True, 'starting_armament': False},
    'Aspects of the Crucible: Tail': {'damage': 'Physical', 'in_generic_pool': True, 'starting_armament': False},
    'Barrier of Gold': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Beast Claw': {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': True},
    'Bestial Sling': {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': False},
    'Bestial Vitality': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Black Blade': {'damage': 'Holy', 'in_generic_pool': True, 'starting_armament': False},
    'Black Flame': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Black Flame Blade': {'damage': 'Buff/Utility', 'in_generic_pool': False, 'starting_armament': False},
    'Black Flame Ritual': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    "Black Flame's Protection": {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Blessing of The Erdtree': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Blessing's Boon": {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Bloodboon': {'damage': 'Fire', 'in_generic_pool': True, 'starting_armament': False},
    'Bloodflame Blade': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Bloodflame Talons': {'damage': 'Fire', 'in_generic_pool': True, 'starting_armament': False},
    "Borealis's Mist": {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Burn- O Flame!': {'damage': 'Buff/Utility', 'in_generic_pool': False, 'starting_armament': False},
    'Catch Flame': {'damage': 'Fire', 'in_generic_pool': True, 'starting_armament': False},
    'Darkness': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Death Lightning': {'damage': 'Lightning', 'in_generic_pool': False, 'starting_armament': False},
    'Discus of Light': {'damage': 'Holy', 'in_generic_pool': False, 'starting_armament': False},
    'Divine Fortification': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Dragonbolt Blessing': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Dragonclaw': {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': False},
    'Dragonfire': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': True},
    'Dragonice': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Dragonmaw': {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': False},
    "Ekzykes's Decay": {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': False},
    'Elden Stars': {'damage': 'Holy', 'in_generic_pool': True, 'starting_armament': False},
    'Electrify Armament': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Erdtree Heal': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Fire's Deadly Sin": {'damage': 'Fire', 'in_generic_pool': True, 'starting_armament': False},
    'Flame Fortification': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Flame Sling': {'damage': 'Fire', 'in_generic_pool': True, 'starting_armament': False},
    'Flame of The Fell God': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Flame- Fall Upon Them': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Flame- Grant Me Strength': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Flame- Protect Me': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Fortissax's Lightning Spear": {'damage': 'Lightning', 'in_generic_pool': False, 'starting_armament': False},
    'Frenzied Burst': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Frozen Lightning Spear': {'damage': 'Lightning', 'in_generic_pool': False, 'starting_armament': False},
    'Giantsflame Take Thee': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Glintstone Breath': {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Golden Lightning Fortification': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Golden Vow': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Great Heal': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Greyoll's Roar": {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': False},
    "Gurranq's Beast Claw": {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': False},
    'Heal': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Honed Bolt': {'damage': 'Lightning', 'in_generic_pool': False, 'starting_armament': False},
    'Howl of Shabriri': {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': False},
    'Immutable Shield': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Lansseax's Glaive": {'damage': 'Lightning', 'in_generic_pool': False, 'starting_armament': False},
    'Law of Causality': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Law of Regression': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Lightning Fortification': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Lightning Spear': {'damage': 'Lightning', 'in_generic_pool': False, 'starting_armament': True},
    'Lightning Strike': {'damage': 'Lightning', 'in_generic_pool': False, 'starting_armament': False},
    'Litany of Proper Death': {'damage': 'Holy', 'in_generic_pool': False, 'starting_armament': False},
    "Lord's Divine Fortification": {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Lord's Heal": {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Magic Fortification': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Magma Breath': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Noble Presence': {'damage': 'Fire', 'in_generic_pool': True, 'starting_armament': False},
    'O- Flame!': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    "Order's Blade": {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Pest Threads': {'damage': 'Physical', 'in_generic_pool': True, 'starting_armament': False},
    "Placidusax's Ruin": {'damage': 'Fire', 'in_generic_pool': True, 'starting_armament': False},
    'Poison Armament': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Poison Mist': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Protection of The Erdtree': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Radagon's Rings of Light": {'damage': 'Holy', 'in_generic_pool': False, 'starting_armament': False},
    'Rejection': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Rotten Breath': {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': False},
    'Scarlet Aeonia': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Scouring Black Flame': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Shadow Bait': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    "Smarag's Glint Breath": {'damage': 'Magic', 'in_generic_pool': False, 'starting_armament': False},
    'Stone of Gurranq': {'damage': 'Physical', 'in_generic_pool': False, 'starting_armament': False},
    'Surge- O Flame!': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Swarm of Flies': {'damage': 'Physical', 'in_generic_pool': True, 'starting_armament': False},
    'The Flame of Frenzy': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    "Theodorix's Magma": {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Triple Rings of Light': {'damage': 'Holy', 'in_generic_pool': False, 'starting_armament': False},
    'Unendurable Frenzy': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Urgent Heal': {'damage': 'Buff/Utility', 'in_generic_pool': True, 'starting_armament': False},
    'Whirl- O Flame!': {'damage': 'Fire', 'in_generic_pool': False, 'starting_armament': False},
    'Wrath of Gold': {'damage': 'Holy', 'in_generic_pool': True, 'starting_armament': True},
}
