"""
Nightreign Weapon Skills - complete datamine-verified list (181 skills)
Sources: SwordArtsTableParam categories, AtkParam damage search,
  build_advisor overrides, game_knowledge existing data, base ER context

Fields:
  affinity: Fire/Lightning/Magic/Holy/None
  damage_types: physical attack types [Standard, Slash, Pierce, Strike]
  innate_status: Hemorrhage/Poison/Frostbite/Madness/Sleep/None
  skill_type: general / unique / shield / bow
  source: datamine / override / context / category
"""

WEAPON_SKILLS_FULL = {
    "Alabaster Lords' Pull": {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    'Ancient Lightning Spear': {'affinity': 'Lightning', 'skill_type': 'unique', 'source': 'override'},
    "Angel's Wings": {'affinity': 'Physical', 'skill_type': 'unique', 'source': 'context'},
    "Assassin's Gambit": {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Barbaric Roar': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Barrage': {'affinity': None, 'damage_types': ['Pierce'], 'skill_type': 'bow', 'source': 'category'},
    'Barricade Shield': {'affinity': None, 'skill_type': 'shield', 'source': 'category'},
    'Bear Witness!': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    "Beast's Roar": {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Black Flame Tornado': {'affinity': 'Fire', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Blade of Death': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Blade of Gold': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'override'},
    'Blood Blade': {'affinity': None, 'innate_status': 'Hemorrhage', 'skill_type': 'general', 'source': 'category'},
    'Blood Tax': {'affinity': None, 'innate_status': 'Hemorrhage', 'skill_type': 'general', 'source': 'category'},
    'Bloodblade Dance': {'affinity': 'Fire', 'damage_types': ['Slash'], 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Bloodboon Ritual': {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'context'},
    "Bloodhound's Finesse": {'affinity': 'Physical', 'skill_type': 'unique', 'source': 'context'},
    "Bloodhound's Step": {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Bloody Slash': {'affinity': None, 'innate_status': 'Hemorrhage', 'skill_type': 'general', 'source': 'category'},
    "Braggart's Roar": {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Bubble Shower': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Buckler Parry': {'affinity': None, 'skill_type': 'shield', 'source': 'category'},
    'Carian Grandeur': {'affinity': 'Magic', 'skill_type': 'general', 'source': 'category'},
    'Carian Greatsword': {'affinity': 'Magic', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Carian Retaliation': {'affinity': 'Magic', 'skill_type': 'general', 'source': 'category'},
    'Charge Forth': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Chilling Mist': {'affinity': None, 'innate_status': 'Frostbite', 'skill_type': 'general', 'source': 'category'},
    'Claw Flick': {'affinity': 'Physical', 'skill_type': 'unique', 'source': 'context'},
    'Contagious Fury': {'affinity': None, 'skill_type': 'unique', 'source': 'buff'},
    'Corpse Piler': {'affinity': 'Fire', 'damage_types': ['Slash'], 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Corpse Wax Cutter': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    'Cragblade': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Cursed-Blood Slice': {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'context'},
    'Death Flare': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'override'},
    'Destined Death': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Determination': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Devourer of Worlds': {'affinity': None, 'skill_type': 'unique', 'source': 'buff'},
    'Double Slash': {'affinity': None, 'damage_types': ['Standard', 'Pierce'], 'skill_type': 'general', 'source': 'category'},
    "Dynast's Finesse": {'affinity': 'Physical', 'damage_types': ['Pierce'], 'skill_type': 'unique', 'source': 'context'},
    'Earthshaker': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Enchanted Shot': {'affinity': None, 'skill_type': 'bow', 'source': 'category'},
    'Endure': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    "Eochaid's Dancing Blade": {'affinity': 'Magic', 'damage_types': ['Standard'], 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Erdtree Slam': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'override'},
    'Eruption': {'affinity': 'Fire', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Establish Order': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    'Familial Rancor': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Fires of Slumber': {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'override'},
    'Flame Dance': {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'context'},
    'Flame Spit': {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'context'},
    'Flame of the Redmanes': {'affinity': 'Fire', 'skill_type': 'general', 'source': 'category'},
    'Flaming Strike': {'affinity': 'Fire', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Flowing Form': {'affinity': 'Physical', 'skill_type': 'unique', 'source': 'context'},
    'Flowing Form (Hammer)': {'affinity': 'Physical', 'skill_type': 'unique', 'source': 'context'},
    'Frenzyflame Thrust': {'affinity': 'Fire', 'innate_status': 'Madness', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Ghostflame Ignition': {'affinity': 'Magic', 'innate_status': 'Frostbite', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Giant Hunt': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Glintblade Phalanx': {'affinity': 'Magic', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Glintstone Dart': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    'Glintstone Pebble': {'affinity': 'Magic', 'skill_type': 'general', 'source': 'category'},
    'Gold Breaker': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    'Golden Land': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'category'},
    'Golden Parry': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'category'},
    'Golden Retaliation': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    'Golden Slam': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'category'},
    'Golden Tempering': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    'Golden Vow': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Gravitas': {'affinity': 'Magic', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Gravity Bolt': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'override'},
    'Great Oracular Bubble': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    'Great-Serpent Hunt': {'affinity': 'Physical', 'skill_type': 'unique', 'source': 'context'},
    'Ground Slam': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    "Hoarah Loux's Earthshaker": {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Hoarfrost Stomp': {'affinity': None, 'innate_status': 'Frostbite', 'skill_type': 'general', 'source': 'category'},
    'Holy Ground': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'category'},
    'I Command Thee, Kneel!': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    'Ice Lightning Sword': {'affinity': 'Lightning', 'skill_type': 'unique', 'source': 'override'},
    'Ice Spear': {'affinity': None, 'innate_status': 'Frostbite', 'skill_type': 'general', 'source': 'category'},
    'Impaling Thrust': {'affinity': None, 'damage_types': ['Pierce'], 'skill_type': 'general', 'source': 'category'},
    'Kick': {'affinity': None, 'damage_types': ['Strike'], 'skill_type': 'general', 'source': 'category'},
    'Knowledge Above All': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'override'},
    'Last Rites': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    'Lifesteal Fist': {'affinity': None, 'innate_status': 'Hemorrhage', 'skill_type': 'general', 'source': 'category'},
    'Lightning Ram': {'affinity': 'Lightning', 'skill_type': 'general', 'source': 'category'},
    'Lightning Slash': {'affinity': 'Lightning', 'skill_type': 'general', 'source': 'game_knowledge'},
    "Lion's Claw": {'affinity': None, 'damage_types': ['Standard'], 'skill_type': 'general', 'source': 'category'},
    "Loretta's Slash": {'affinity': 'Magic', 'damage_types': ['Slash'], 'skill_type': 'general', 'source': 'game_knowledge'},
    "Loretta's Slash (Sickle)": {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    'Magic Dagger': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    'Magma Guillotine': {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Magma Shower': {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'override'},
    'Mighty Shot': {'affinity': None, 'damage_types': ['Pierce'], 'skill_type': 'bow', 'source': 'category'},
    "Miquella's Ring of Light": {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'override'},
    'Mists of Slumber': {'affinity': None, 'skill_type': 'unique', 'source': 'buff'},
    'Moonlight Greatsword': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'override'},
    "Nebula (Bastard's Stars)": {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'override'},
    'Nebula (Wing of Astel)': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'override'},
    'Night-and-Flame Stance': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'No Skill': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Oath of Vengeance': {'affinity': None, 'skill_type': 'unique', 'source': 'buff'},
    "Onyx Lords' Repulsion": {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    'Oracular Bubble': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    "Ordovis's Vortex": {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    'Parry': {'affinity': None, 'skill_type': 'shield', 'source': 'category'},
    'Phantom Slash': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Piercing Fang': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Poison Moth Flight': {'affinity': None, 'innate_status': 'Poison', 'skill_type': 'general', 'source': 'category'},
    'Poisonous Mist': {'affinity': None, 'innate_status': 'Poison', 'skill_type': 'general', 'source': 'category'},
    'Prayerful Strike': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'game_knowledge'},
    "Prelate's Charge": {'affinity': 'Fire', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Quickstep': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    "Radahn's Rain": {'affinity': 'Physical', 'skill_type': 'unique', 'source': 'context'},
    'Rain of Arrows': {'affinity': None, 'damage_types': ['Pierce'], 'skill_type': 'bow', 'source': 'category'},
    'Rallying Standard': {'affinity': None, 'skill_type': 'unique', 'source': 'buff'},
    'Raptor of the Mists': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Reduvia Blood Blade': {'affinity': None, 'innate_status': 'Hemorrhage', 'skill_type': 'unique', 'source': 'category'},
    'Regal Beastclaw': {'affinity': 'Physical', 'skill_type': 'unique', 'source': 'context'},
    'Regal Roar': {'affinity': None, 'skill_type': 'unique', 'source': 'buff'},
    'Repeating Thrust': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    "Rosus's Summons": {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    "Royal Knight's Resolve": {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Ruinous Ghostflame': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'override'},
    'Sacred Blade': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Sacred Order': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Sacred Phalanx': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'override'},
    'Sacred Ring of Light': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'category'},
    'Sea of Magma': {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'override'},
    'Seppuku': {'affinity': None, 'innate_status': 'Hemorrhage', 'skill_type': 'general', 'source': 'category'},
    'Shared Order': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'category'},
    'Shield Bash': {'affinity': None, 'skill_type': 'shield', 'source': 'category'},
    'Shield Crash': {'affinity': None, 'skill_type': 'shield', 'source': 'category'},
    'Shriek of Milos': {'affinity': None, 'skill_type': 'unique', 'source': 'buff'},
    "Siluria's Woe": {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    'Sky Shot': {'affinity': None, 'skill_type': 'bow', 'source': 'category'},
    'Sorcery of the Crozier': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    'Soul Stifler': {'affinity': None, 'skill_type': 'unique', 'source': 'buff'},
    'Spearcall Ritual': {'affinity': 'Physical', 'skill_type': 'unique', 'source': 'context'},
    'Spectral Lance': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Spinning Chain': {'affinity': None, 'damage_types': ['Strike'], 'skill_type': 'general', 'source': 'category'},
    'Spinning Slash': {'affinity': None, 'damage_types': ['Slash'], 'skill_type': 'general', 'source': 'category'},
    'Spinning Slash (Dragon Halberd)': {'affinity': 'Lightning', 'skill_type': 'unique', 'source': 'context'},
    'Spinning Strikes': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Spinning Weapon': {'affinity': 'Magic', 'damage_types': ['Standard'], 'skill_type': 'general', 'source': 'category'},
    'Spinning Wheel': {'affinity': 'Physical', 'skill_type': 'unique', 'source': 'context'},
    'Square Off': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Stamp (Sweep)': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Stamp (Upward Cut)': {'affinity': None, 'damage_types': ['Standard'], 'skill_type': 'general', 'source': 'category'},
    'Starcaller Cry': {'affinity': 'Magic', 'damage_types': ['Strike'], 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Storm Assault': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Storm Blade': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Storm Kick': {'affinity': 'Lightning', 'skill_type': 'unique', 'source': 'context'},
    'Storm Ruler': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    'Storm Stomp': {'affinity': None, 'damage_types': ['Standard'], 'skill_type': 'general', 'source': 'category'},
    'Storm Wall': {'affinity': None, 'skill_type': 'shield', 'source': 'category'},
    'Stormcaller': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Surge of Faith': {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Sword Dance': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    "Taker's Flames": {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'override'},
    "The Queen's Black Flame": {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'override'},
    "Thops's Barrier": {'affinity': 'Magic', 'skill_type': 'general', 'source': 'category'},
    'Through and Through': {'affinity': None, 'damage_types': ['Pierce'], 'skill_type': 'bow', 'source': 'category'},
    'Thunderbolt': {'affinity': 'Lightning', 'skill_type': 'general', 'source': 'game_knowledge'},
    'Thundercloud Form': {'affinity': 'Lightning', 'skill_type': 'unique', 'source': 'override'},
    'Thunderstorm': {'affinity': 'Lightning', 'skill_type': 'unique', 'source': 'override'},
    'Tongues of Fire': {'affinity': 'Fire', 'skill_type': 'unique', 'source': 'context'},
    'Torch Attack': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Transient Moonlight': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'game_knowledge'},
    "Troll's Roar": {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Unblockable Blade': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Unblockable Blade (Pata)': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'context'},
    'Unsheathe': {'affinity': None, 'damage_types': ['Standard', 'Pierce'], 'skill_type': 'general', 'source': 'category'},
    'Vacuum Slice': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Viper Bite': {'affinity': None, 'skill_type': 'unique', 'source': 'buff'},
    'Vow of the Indomitable': {'affinity': 'Holy', 'skill_type': 'general', 'source': 'category'},
    'War Cry': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    'Waterfowl Dance': {'affinity': 'Physical', 'damage_types': ['Slash', 'Pierce'], 'skill_type': 'unique', 'source': 'context'},
    'Wave of Destruction': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'game_knowledge'},
    'Wave of Gold': {'affinity': 'Holy', 'skill_type': 'unique', 'source': 'override'},
    'Waves of Darkness': {'affinity': 'Magic', 'skill_type': 'general', 'source': 'category'},
    "White Shadow's Lure": {'affinity': None, 'innate_status': 'Sleep', 'skill_type': 'general', 'source': 'category'},
    'Wild Strikes': {'affinity': None, 'skill_type': 'general', 'source': 'category'},
    "Wolf's Assault": {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
    'Zamor Ice Storm': {'affinity': 'Magic', 'skill_type': 'unique', 'source': 'context'},
}